import sqlite3
conn = sqlite3.connect('solution/db/knowledge_base.db')
cur = conn.cursor()
rows = cur.execute("SELECT project_name, category, value_inr FROM projects WHERE client_name = 'Trishakti Power Generation Corporation'").fetchall()
epc = sum(r[2] for r in rows if r[1] == 'industrial epc')
roads = sum(r[2] for r in rows if r[1] == 'roads highways')
print(f"Total Trishakti: {sum(r[2] for r in rows):,}")
print(f"industrial epc: {epc:,}")
print(f"roads highways: {roads:,}")
print(f"Sum of both: {epc + roads:,}")
print(f"Diff of both: {abs(epc - roads):,}")
